CREATE SCHEMA `cineclube` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
USE cineclube;
CREATE TABLE `cineclube`.`resenhas` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nomeDoFilme` VARCHAR(255) NULL,
    `nome` VARCHAR(255) NULL,
    `email` VARCHAR(255) NULL,
    `resenha` VARCHAR(255) NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8MB4 COLLATE = UTF8MB4_BIN;

CREATE TABLE `cineclube`.`favoritos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nomeDoFilme` VARCHAR(255) NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8MB4 COLLATE = UTF8MB4_BIN;